### ISSUE TITLE
(IMPORT FAILED) ComfyUI\custom_nodes\ControlAltAI-Nodes

### ISSUE THREAD

**Issue by shschong** [Tavris1/ComfyUI-Easy-Install#1]
File "C:\Users\User\Documents\ComfyUI\ComfyUI-Easy-Install-EP24\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes\flux_attention_control_node.py", line 10, in <module> from xformers.ops import memory_efficient_attention as xattention
ModuleNotFoundError: No module named 'xformers'

**Comment by gseth** [comment]
XFormers is now needed for the flux region spatial control to work. You can install Xformers without breaking any other dependency by using the following command:

Go to the comfy portable python embedded folder and open CMD.

and run the following command:

`python.exe -m pip install xformers==0.0.28.dev890 --no-dependencies`

After that confirm by

`python.exe -m pip show xformers`

And it should show you something like:

```
Name: xformers
Version: 0.0.28.dev890
Summary: XFormers: A collection of composable Transformer building blocks.
Home-page: https://facebookresearch.github.io/xformers/
Author: Facebook AI Research
Author-email: oncall+xformers@xmail.facebook.com
License:
Location: Q:\ComfyUI\ComfyUI_2024\python_embeded\Lib\site-packages
Requires: numpy, torch
Required-by:
```
